Simple servlet to search Apache Solr
NASA-PDS/registry-legacy-server pull request #2
Opened 2024-02-03 23:45 UTC by jordanpadams

## 🗒️ Summary
Simple servlet to sit between keyword search / public access and Solr.

## ⚙️ Test Data and/or Report
```
# Build package
% mvn package

# Move package to Apache Tomcat webapps dir
% mv target/*.war /path/to/tomcat/webapps

# Test some queries from http://localhost:8080/registry-legacy-server/search
```

Some test queries:
* http://localhost:8080/registry-legacy-server/search?q=*:*
  * then select any of the available facets to see them work

## ♻️ Related Issues

Resolves #1

2024-02-04 00:10 UTC, nutjob4life commented on src/changes/changes.xml
> +    <author email="Sean.Hardman@jpl.nasa.gov">Sean Hardman</author>
Really? Sean Hardman? 😁

2024-02-04 00:11 UTC, nutjob4life commented on src/main/assembly/tar-assembly.xml
> +  Copyright 2014, by the California Institute of Technology.
2024 😉

2024-02-04 00:13 UTC, nutjob4life commented on src/main/java/gov/nasa/pds/search/servlet/RegistryLegacyServlet.java
> +      // LOG.info(String.valueOf(solrResponse.statusCode()));
Maybe this is just me, but I don't like to see commented-out code unless there's an explanation of why it's commented-out. Better to add that or just delete it!

2024-02-04 00:15 UTC, nutjob4life requested changes
I couldn't actually get this to run with Tomcat 10, 9, 8, or 7 (via Docker) but maybe that's a "me problem" 😆

Otherwise the servlet implementation looks fine. I'd just like to see the commented-out code explained or deleted 👍

2024-02-04 00:15 UTC, nutjob4life commented on src/main/java/gov/nasa/pds/search/servlet/SolrSearch.java
> +//  public SolrDocumentList search(String query, int start, int rows) throws MalformedURLException, SolrServerException {
Can we just delete all this? See earlier remark about commented-out code. It should be explained or deleted—with prejudice 😈

2024-02-05 18:11 UTC, jordanpadams commented
@nutjob4life thanks for the review. moved to https://github.com/NASA-PDS/search-ui-legacy/pull/6 to bring some of these components together to simplify the deployment and since they are so tightly coupled.

2024-02-05 18:12 UTC, closed without merging